print_info() :-
    write('Welcome to RPG Material Planner!!!'),
    nl,
    write('Here are questions you can ask: '),
    nl,
    write('- What materials required for upgrading to [career from the list below]?'),
    nl,
    write('- How many [material type from the list below] required for upgrading to [career from the list below]?'),
    nl,
    write('- Can I upgrade to [career from the list below]?'),
    nl,
    write('- How many [material type from the list below] I still need for upgrading to [career from the list below]?'),
    nl,
    write('- What materials can be earned from stage [an integer from 1 to 6]?'),
    nl,
    write('- How many [material type from the list below] can be earned from stage [an integer from 1 to 6]?'),
    nl,
    write('- How many times do I have to clear stage [an integer from 1 to 6] for upgrading to [career from the list below]?'),
    nl,
    write('- How long does stage [an integer from 1 to 6] take?'),
    nl,
    write('- How can I upgrade to [career from the list below]?'),
    nl,
    write('- What is the best way for me to upgrade to [career from the list below]?'),
    nl,
    write('**************'),
    nl,
    write('Careers: knight, fighter, mage'),
    nl,
    write('Material types: magic, shield, attack'),
    nl,
    write('Stages: 1, 2, 3, 4, 5, 6'),
    nl,
    write('**************'),
    nl,
    write('COMMANDS: '),
    nl,
    write('- Ask questions: ask(Ans).'),
    nl,
    write('- Print info: print_info(). '),
    nl.
